### ISSUE TITLE
20230405 수정사항 정리

### ISSUE THREAD

**Issue by developerChans** [DKUcouncilhomepage/student-council-homepage-frontend#214]
- [x] EveryUniv/student-council-homepage-frontend#215 
- [x] EveryUniv/student-council-homepage-frontend#216 
- [x] EveryUniv/student-council-homepage-frontend#217 
- [x] EveryUniv/student-council-homepage-frontend#218 
- [x] EveryUniv/student-council-homepage-frontend#219 
- [x] EveryUniv/student-council-homepage-frontend#220 
- [x] EveryUniv/student-council-homepage-backend#259 
- [x] EveryUniv/student-council-homepage-frontend#222 
- [x] EveryUniv/student-council-homepage-frontend#223 
- [x] EveryUniv/student-council-homepage-backend#234 
- [x] EveryUniv/student-council-homepage-backend#235
