### ISSUE TITLE
[FEATURE] 2023 단페스타를 위한 티켓팅 페이지

### ISSUE THREAD

**Issue by developerChans** [DKUcouncilhomepage/student-council-homepage-frontend#279]
**Describe the new feature**
- 마감 기한: `2023-05-02`
- 작업 내용: 
홈페이지 회원가입자를 위한, 티켓팅 페이지 완성
- 관련 문서 또는 링크: 

Figma: https://www.figma.com/file/gakPHo9KW7lrbRKKDDWppq/%ED%8B%B0%EC%BC%93%ED%8C%85?node-id=0-1&t=peYPns8BI92A8GTc-0

Backend: @won983212 -> swagger 예정

**Todos**
- [ ] 입장 페이지 만들기

![image](https://user-images.githubusercontent.com/68864422/233919199-2051a79e-7104-4433-891a-c8f581b066e8.png)
위 버튼 2개에서 각 버튼은 해당하는 날짜에 해당되는 페이지로 이동한다. 하지만, 다음페이지로 이동하기 전에 시간을 확인해주어야한다.
시간의 기준은 다음과 같다.
5월 17일 티켓팅 페이지: 5월 13일 12:00시 부터 입장 가능
5월 18일 티켓팅 페이지: 5월 13일 18:00시 부터 입장 가능

+ 버튼의 회색배경같은 경우 단색의 사진으로 채워두자. (나중에 디자인팀에서 제공하는 사진으로 변경할 예정)

- [ ]  신청 페이지 만들기
![image](https://user-images.githubusercontent.com/68864422/233919370-1c4d6f9a-dbce-4da2-8d58-c81e0ebae735.png)

체크박스와 captcha 를 구현해야한다. 나머지 사항은 디자인 배경에 포함 될 예정이다.
따라서, 우선 밖에 회색배경같은 경우 단색의 사진으로 채워두자. 

+ 회색배경은 늘어날 수 있다. 따라서 체크박스와 captcha는 아래를 기준으로 setting해줘야한다.
+ 17일과 18일은 둘다 회색배경 사진이 다르다.

- [ ] 신청 완료 페이지 만들기
신청이 완료되었다면, 다음과 같은 예비번호를 Server에서 받아서 사용자에게 보여줘야한다.
![image](https://user-images.githubusercontent.com/68864422/233920221-f326e487-c39c-4b8d-bb99-1bae576c0912.png)

+ 회색배경 또한 디자인팀에서 제공 예정 두번쨰 페이지 회색배경과 다름

- [ ] 예외처리하기
아마 Server에서 message로 대부분 보내 줄 것이지만, 아래 목록중에 없거나, 추가 되어야 한다고 판단하는 것은 추가해주길 바람
1. 시간이 안된 경우 -> ~~부터 신청이 가능합니다.
2. 이미 신청이 완료된 경우 -> 이미 티켓팅 이벤트에 참여하였습니다.
3. 추가예정
**Additional text**
- code상에서 page 구조는 회의를 통해 더 진행한다. 이부분의 의견은 @ho991217 님의 의견을 적극적으로 반영한다.
