### ISSUE TITLE
[FEATURE] 셔틀버스 페이지

### ISSUE THREAD

**Issue by developerChans** [DKUcouncilhomepage/student-council-homepage-frontend#295]
**Describe the new feature**
- 마감 기한: `2023-07-31`
- 작업 내용: `셔틀버스 관련 페이지 완성`
- 관련 문서 또는 링크: 

**꼭 아래 figma 링크를 이용하길 바람**

figma: [https://www.figma.com/file/6x3HpH8FKUJSmPSWNB1RqS/%EA%B7%80%ED%96%A5%EB%B2%84%EC%8A%A4?type=design&node-id=0-1&mode=design&t=KdU98xHFnhhOwWr0-0](https://www.figma.com/file/6x3HpH8FKUJSmPSWNB1RqS/%EA%B7%80%ED%96%A5%EB%B2%84%EC%8A%A4?type=design&node-id=0-1&mode=design&t=KdU98xHFnhhOwWr0-0)

Backend 기획: 
[https://github.com/EveryUniv/student-council-homepage-backend/issues/405](https://github.com/EveryUniv/student-council-homepage-backend/issues/405)

승차권은 다음과 같은 프로세스를 거친다.
유저의 승차권 신청 -> 관리자 입금확인 -> 관리자 수동 확정 -> 승차권 발급 확정
유저가 승차권 취소 -> 관리자 환불 진행 -> 승차권 취소 확정

**Todos**
귀향버스 페이지에는 여러 상태가있다.
1. 승차권이 없는 경우
2. 승차권이 있는 경우
3. 승차권이 신청상태 인 경우
4. 승차권을 취소상태 인 경우

외에, 티켓 확인 페이지가 존재한다.

- [x] `승차권이 없는 경우`
- [x] `승차권이 있는 경우`
- [x] `승차권이 신청상태인 경우`
- [x] `승차권이 취소상태인 경우`
- [x] 티켓 조회 페이지
- [x] Desktop
- [x] Mobile

**Additional text**
1.  `승차권이 없는 경우`
승차권이 없는 경우 모든 승차권에 대해서 신청 할 수 있다.

{
  호차(ex: 1호선, 1호선-1호차 등)
  경로
  종착지
  잔여석/전체석
}
+ 신청버튼

신청 버튼을 누를시 해당 버스를 신청하는 모달창이 발생하여야한다.

2. `승차권이 있는 경우`
승차권이 확정되어 있는 경우 해당 승차권 호선을 제외하곤 신청버튼이 회색으로 처리되며, 누를 수 없게 된다.
다만, 확정된 승차권에 한하여 신청버튼이 아닌 "취소"버튼이 활성화가 된다.
취소 버튼을 누를 시 취소 관련 모달창이 발생한다.

3. `승차권이 신청상태인 경우`
숭차권이 신청상태인 경우, 신청상태인 호선 제외하곤, 신청버튼이 회색으로 처리되며, 해당 버튼은 "확정 대기" 의 텍스트를 가진 비활성화 버튼으로 되어있어야한다.

해당 상태인 경우 유저는 아무것도 모데.

4. `승차권이 취소상태인 경우`
3번 경우에서 확정대기 대신 취소 대기 로 변경한다.

**Comment by developerChans** [comment]
@gaeunnlee 셔틀버스 배너
[귀향버스 배너.zip](https://github.com/EveryUniv/student-council-homepage-frontend/files/12090188/default.zip)
